version: "3.9"

services:
  mongo:
    image: mongo:6.0
    container_name: url_shortener_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - urlnet

  backend:
    build: ./backend
    container_name: url_shortener_backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "5050:5000"
    depends_on:
      - mongo
    networks:
      - urlnet

volumes:
  mongo_data:

networks:
  urlnet: